Update shell files

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -5,19 +5,37 @@ set -euo pipefail
 current_script_path=${BASH_SOURCE[0]}
 plugin_dir=$(dirname "$(dirname "$current_script_path")")
 
+case "$OSTYPE" in
+darwin*) os_type="macos" ;;
+linux*) os_type="linux" ;;
+*) fail "Unsupported platform" ;;
+esac
+
+case $(uname -m) in
+x86_64*) arch="x64" ;;
+aarch64*) arch="arm64" ;;
+*) fail "Unsupported architecture" ;;
+esac
+
+if [[ "$os_type" == "linux" && "$arch" == "arm64" ]]; then
+	fail "Unsupported architecture"
+fi
+
+platform="$os_type-$arch"
+
 # shellcheck source=./lib/utils.bash
 source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
 release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
 
 # Download tar.gz file to the download directory
-download_release "$ASDF_INSTALL_VERSION" "$release_file"
+download_release "$platform" "$ASDF_INSTALL_VERSION" "$release_file"
 
 #  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+# tar -xvzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
 
 # Remove the tar.gz file since we don't need to keep it
 rm "$release_file"
